# workflow which lints and checks the code on every push and pull request
name: Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v4

      # https://github.com/actions/setup-python
      - name: set up python
        uses: actions/setup-python@v5
        with:
          cache: "pip" # caching pip dependencies
          python-version: "3.12"

      - name: install OS-level deps
        run: |-
          #!/bin/sh
          printf '%s\n' "running as $(id) in $(pwd)" >&2;
          set -eux
          export DEBIAN_FRONTEND=noninteractive;
          AG="sudo apt-get -yq --no-install-recommends";
          $AG update;
          $AG install \
            freetds-dev \
            unixodbc-dev \
          ;

      - name: install python packages
        run: |-
          #!/bin/sh
          SELF=$(basename "$0" ".sh")
          printf '%s\n' "${SELF} running as $(id) in $(pwd)" >&2;
          set -eux

          set --
          for requirements_file in requirements.txt requirements.dev.txt requirements-dev.txt; do
            if [ -f "$requirements_file" ]; then
              set -- "$@" -r "$requirements_file"
            fi
          done
          pip install --upgrade "$@"

      # https://github.com/pre-commit/action
      - name: run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch
