name: Docker

"on":
  push:
    branches:
      - main
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - main

jobs:
  image:
    uses: edencehealth/workflows/.github/workflows/dockerimage.yml@v1
    with:
      container_name: pyodbcbase
      push_readme: README.md
      push: true
    secrets: inherit
